Proposal for blockchain-carbon-accounting to Hyperledger Labs.
hyperledger-labs/hyperledger-labs.github.io pull request #156
Opened 2020-11-11 03:28 UTC by opentaps

Thanks @C0rWin for looking through it.

Signed-off-by: Si Chen <sichen@opensourcestrategies.com>

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal
- [ ] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

2020-11-11 07:54 UTC, C0rWin approved these changes

2020-11-12 20:40 UTC, vipinsun requested changes
Please have BARTEM@il.ibm.com comment on this PR saying that he sponsored the PR-
Or is @C0rWin Artem Barger?
If you are bringing in an outside repository from opentaps, it needs DCO sign off as well. In case you do not have this DCO please look at documentation which discussed how to squash commit with a dco before moving code in.

2020-11-12 20:40 UTC, vipinsun commented on labs/blockchain-carbon-accounting.md
> +_Provide the name of your sponsor. A sponsor is required and must be a maintainer of one of the Hyperledger projects, a TSC member, or a WG chair._
Remove this line which is left over from the template

2020-11-12 22:15 UTC, C0rWin commented
> Or is @C0rWin Artem Barger?

Yes, I'm :)

2020-11-13 20:48 UTC, lehors approved these changes
I think it'd be good to explain the motivation for organizations to participate in such a system - is that to fulfill some legal obligations? because it will help improve their public image? something else?

This is however not a requirement for this proposal to get approved though. I'm fine with it.

2020-11-13 20:48 UTC, lehors commented on labs/blockchain-carbon-accounting.md
> +title: Lab Proposal Document
I believe this should be set to the lab's name instead.

2020-11-13 22:46 UTC, vipinsun approved these changes

2020-11-13 22:48 UTC, vipinsun commented
Merging as requested changes have been done.

2020-11-13 22:49 UTC, merged

2020-11-17 00:02 UTC, opentaps commented
Thanks @lehors!  We wrote about it on the wiki:
https://wiki.hyperledger.org/display/CASIG/Carbon+Accounting+and+Certification+Working+Group

If you'd like we can add it to the lab proposal as well.

-----
Si Chen
Open Source Strategies, Inc.

Video: Fighting Climate Change with Blockchain and Open Source
<https://youtu.be/NgxNWXa_IjE>


On Fri, Nov 13, 2020 at 12:49 PM Arnaud J Le Hors <notifications@github.com>
wrote:

> *@lehors* approved this pull request.
>
> I think it'd be good to explain the motivation for organizations to
> participate in such a system - is that to fulfill some legal obligations?
> because it will help improve their public image? something else?
>
> This is however not a requirement for this proposal to get approved
> though. I'm fine with it.
> ------------------------------
>
> In labs/blockchain-carbon-accounting.md
> <https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/156#discussion_r523217678>
> :
>
> > @@ -0,0 +1,32 @@
> +---
> +layout: default
> +title: Lab Proposal Document
>
> I believe this should be set to the lab's name instead.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/156#pullrequestreview-530404062>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANAS4OTPJQQHQN44CM6PVDSPWLTZANCNFSM4TROMVFQ>
> .
>