Volunteering to be Lab Steward
hyperledger-labs/hyperledger-labs.github.io pull request #214
Opened 2022-06-17 18:34 UTC by anandbanik

Volunteering to be Lab Steward
TSC Sponsor - @arsulegai.
Signed-off-by: Anand Banik <anand.banik@walmart.com>

2022-06-18 18:57 UTC, ryjones requested changes
Please sort by GitHub alias - you would be first in the list

2022-06-19 19:32 UTC, anandbanik commented
hi @ryjones, I have sorted based on alias. Thank you!

2022-06-20 19:59 UTC, ryjones approved these changes

2022-06-21 07:07 UTC, arsulegai approved these changes
Anand will be great addition to the stewards group. I personally encourage new & (distributed) more representations in the community, taking up responsibilities.

2022-06-23 14:13 UTC, merged