Weft Proposal
hyperledger-labs/hyperledger-labs.github.io pull request #217
Opened 2022-07-04 13:39 UTC by mbwhite

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

## Checklist for Hyperledger Lab Proposal PR

- [x] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [x] Make sure your changes are committed with the proper sign-off
- [x] Use the labs name as the PR title
- [x] Copy the short description of the proposal as the description of the PR
- [x] Remove this checklist section
- [x] Submit your PR and the labs stewards will review your proposal
- [x] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

2022-07-04 13:44 UTC, jt-nti commented
I'm happy to sponsor this proposal

2022-07-04 16:33 UTC, anandbanik reviewed
Hi @mbwhite,
Looks good to me, but since not all of the commits on the referenced repo are signed-off, you will have to push the code to the new repo under hyperledger-labs org with single sign-off. 
Thanks!

2022-07-04 16:37 UTC, anandbanik commented
Also, please ensure to add the Apache 2.0 license file as mentioned [here](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/main/LICENSE)

2022-07-05 08:13 UTC, jt-nti commented
@anandbanik it would be a pity to lose the commit history- would it be ok to update all the commits with a sign-off instead?

2022-07-05 15:06 UTC, anandbanik commented
Hi @jt-nti Sure. Please let me know once all the git commits are signed-off. Thanks!

2022-07-05 21:32 UTC, tkuhrt commented on labs/fabric-weft.md
> +Simple command line utility and module, to help work Hyperledger Fabric, and other instations such as the IBM Blockchain Platform (IBP) and convert resources between them. This is intended to be a co
Not sure if this is what you meant
```suggestion
Simple command line utility and module, to help work Hyperledger Fabric, and other instantiations such as the IBM Blockchain Platform (IBP) and convert resources between them. This is intended to be a complement to the existing tools for each product. A lot of the code here is based on that in hyperledger/fabric-samples
```

2022-07-05 21:33 UTC, tkuhrt commented on labs/fabric-weft.md
> +- application wallets and idenities for the Client SDKs to use
```suggestion
- application wallets and identities for the Client SDKs to use
```

2022-07-05 21:33 UTC, tkuhrt commented on labs/fabric-weft.md
> +For example packaing chaincode the cli is
```suggestion
For example packaging chaincode the cli is 
```

2022-07-05 21:36 UTC, tkuhrt requested changes
Before we can transfer the existing repository, we will need the following done in that repository:
1. Add the Apache LICENSE file
2. Ensure that all commits have DCO sign-off completed.

2022-07-08 15:50 UTC, tkuhrt commented
> > Before we can transfer the existing repository, we will need the following done in that repository:
> > 
> > 1. Add the Apache LICENSE file
> > 2. Ensure that all commits have DCO sign-off completed.
> 
> @tkuhrt thanks (sorry I missed the notification) - can happily do that... personally I don't mind push everything in one go... but no harm in trying to keep the history

No worries. Whatever you want regarding DCO sign-off. Just let us know which direction you want to proceed.

2022-07-08 16:28 UTC, tkuhrt approved these changes

2022-07-08 16:31 UTC, mbwhite commented
@tkuhrt there's not a lot of value in the commit history I think in this case; happy to push it all together. 

one other question - this has previously published a module to npm (under the original orgs namespace) - what's the process in hyperledger-labs?

2022-07-08 16:34 UTC, tkuhrt commented
> @tkuhrt there's not a lot of value in the commit history I think in this case; happy to push it all together.
Sounds good.

> one other question - this has previously published a module to npm (under the original orgs namespace) - what's the process in hyperledger-labs?
@ryjones : Can you help with this question?

2022-07-08 16:55 UTC, anandbanik commented
> > @tkuhrt there's not a lot of value in the commit history I think in this case; happy to push it all together.
> 
> Sounds good.
> 
> > one other question - this has previously published a module to npm (under the original orgs namespace) - what's the process in hyperledger-labs?
> 
> @ryjones : Can you help with this question?

@mbwhite One option is to use github actions to publish the npm module as github package under the hyperledger-labs org.
would like to hear @ryjones opinion on it.

2022-07-14 17:11 UTC, merged

2022-07-14 17:12 UTC, ryjones commented
@mbwhite please transfer the repo to me and I will put it here