Hyperledger Splice
hyperledger-labs/hyperledger-labs.github.io pull request #261
Opened 2024-02-01 19:55 UTC by waynecollier-da

Reference applications for funding, operating, and incentivizing the use of a decentralized, public Canton synchronizer. Includes the Amulet reference application for creating native payment utilities for Canton synchronizers and Daml applications.

2024-02-01 20:07 UTC, tkuhrt requested changes
Thanks for the submission. I agree to be a sponsor for this lab. One minor change, and then I will approve.

2024-02-02 15:54 UTC, tkuhrt commented on labs/images/Super Validator Architecture Diagram for Hyperledger Splice-1.jpg
Can we change name of the diagram too? Also, it looks like the diagram did not update to remove the Hyperledger?

2024-02-02 15:55 UTC, tkuhrt commented on labs/images/Super Validator Architecture Diagram for Hyperledger Splice-2.jpg
Similar comment to the other diagram.

2024-02-02 15:55 UTC, waynecollier-da commented on labs/splice.md
> +# Hyperledger Splice
Ok will fix.

2024-02-02 15:56 UTC, waynecollier-da commented on labs/images/Super Validator Architecture Diagram for Hyperledger Splice-1.jpg
Yep, will fix

2024-02-02 17:14 UTC, waynecollier-da commented
Hi, @tkuhrt I think all the fixes are done now

2024-02-02 17:39 UTC, tkuhrt approved these changes

2024-02-04 08:42 UTC, knagware9 approved these changes
I appove this lab.

2024-02-04 10:25 UTC, nidhi-singh02 approved these changes
Looks great!

2024-02-04 10:26 UTC, merged