new project space
hyperledger-labs/hyperledger-labs.github.io pull request #277
Opened 2024-08-08 20:26 UTC by urgetolearn

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal
- [ ] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

2024-08-09 14:32 UTC, tkuhrt commented
As a first step, please add DCO sign-off to this commit. Please see the instructions on the [checks tab](https://github.com/hyperledger-labs/hyperledger-labs.github.io/pull/277/checks?check_run_id=28537773455)

2024-08-09 14:33 UTC, tkuhrt commented on proposal-template.md
Please do not change this file. Please copy the template into the labs folder with as `name_of_lab.md`. Then make the changes specified.

2024-08-09 14:34 UTC, tkuhrt commented on proposal-template.md
>  _Enter the Github IDs for the set of initial committers._
After you copy the template, you will need to fill in all details of the template.

2024-08-09 14:39 UTC, tkuhrt requested changes
Please make requested changes

2024-08-11 04:18 UTC, urgetolearn commented
This PR was accidentally created, I have now created a new PR for the project proposal.

2024-08-11 04:18 UTC, closed without merging