JsonLD VC BBS Go
hyperledger-labs/hyperledger-labs.github.io pull request #280
Opened 2024-08-22 16:22 UTC by iliecirciumaru

## Checklist for Hyperledger Lab Proposal PR

- [ ] Read [README.md](https://github.com/hyperledger-labs/hyperledger-labs.github.io/blob/master/README.md) carefully
- [ ] Make sure your changes are committed with the proper sign-off
- [ ] Use the labs name as the PR title
- [ ] Copy the short description of the proposal as the description of the PR
- [ ] Remove this checklist section
- [ ] Submit your PR and the labs stewards will review your proposal
- [ ] Ask your sponsor to confirm sponsorship by stating so in a comment to the PR

2024-08-22 16:33 UTC, tkuhrt requested changes
@denyeart @mbrandenburger : Can you confirm your sponsorship? Also, is this something that is already work that has been done in one of the Aries sub-projects?

2024-08-22 16:33 UTC, tkuhrt commented on labs/jsonld-vc-bbs-go.md
> +This library fits into The Linux Foundation Decentralized-Trust branch. It implements issuance, verification, proof generation of [W3C JSON-LD](https://decentralized-id.com/web-standards/w3c/verifiab
```suggestion
This library implements issuance, verification, proof generation of [W3C JSON-LD ZKP with BBS+ Verifiable Credentials](https://decentralized-id.com/web-standards/w3c/verifiable-credentials/data-integrity-bbs+/) in Golang. The initially supported standards are `BbsBlsSignature2020` and `BbsBlsSignatureProof2020`. Later we will add new standards as they are adopted.
```

2024-08-22 16:37 UTC, iliecirciumaru commented
> @denyeart @mbrandenburger : Can you confirm your sponsorship? Also, is this something that is already work that has been done in one of the Aries sub-projects?

The functionality planned for this repo is partially available in the `https://github.com/hyperledger-archives/aries-framework-go`, but this repository is archived. I plan new repo to be very focused, like analogical libraries for Verifiable Credentials available in the JavaScript/TypeScript

2024-08-22 17:24 UTC, denyeart commented
I agree to be a sponsor!

2024-08-23 06:38 UTC, mbrandenburger commented
I support this proposal. While I think labs is a good place for this project, I am wondering if it could also be project of aries? @swcurran @ale-linux WDYT?

2024-08-23 14:50 UTC, swcurran commented
There is the https://github.com/hyperledger/aries-bbs-go that was extracted from the Aries Framework Go after it was archived.  @ale-linux knows a lot more about that.  There may be synergies between the two.

2024-08-23 14:57 UTC, iliecirciumaru commented
> There is the https://github.com/hyperledger/aries-bbs-go that was extracted from the Aries Framework Go after it was archived. @ale-linux knows a lot more about that. There may be synergies between the two.

Correct, this library will use `https://github.com/hyperledger/aries-bbs-go` for crypto-operations. Repository code will concern mainly operations with JSON-LD Verifiable Credential, but not crypto itself

2024-08-23 15:15 UTC, swcurran commented
That makes sense — I wondered the level of the implementation.  Are you doing a W3C [VC-DI-BBS](https://github.com/w3c/vc-di-bbs) implementation?

2024-08-26 11:51 UTC, iliecirciumaru commented
> That makes sense — I wondered the level of the implementation. Are you doing a W3C [VC-DI-BBS](https://github.com/w3c/vc-di-bbs) implementation?

I want to support eventually two standards:
- [old standard 2020](https://w3c-ccg.github.io/ld-cryptosuite-registry/#bbs-signature-2020)
- [new standard 2023](https://www.w3.org/TR/vc-di-bbs/)

Reasons to support old standard:
1. The code already exists, so I need only to publish it
2. Another open source libraries depend on it

2024-08-27 09:09 UTC, iliecirciumaru commented on labs/jsonld-vc-bbs-go.md
> +This library fits into The Linux Foundation Decentralized-Trust branch. It implements issuance, verification, proof generation of [W3C JSON-LD](https://decentralized-id.com/web-standards/w3c/verifiab
Changed the description

2024-08-27 11:20 UTC, vipinsun approved these changes

2024-08-27 11:51 UTC, mbrandenburger approved these changes

2024-08-27 14:35 UTC, tkuhrt approved these changes

2024-08-27 14:35 UTC, merged